version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.0
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch:9200"
    volumes:
      - ./conf:/usr/share/logstash/pipeline
      - ./patterns:/etc/logstash/patterns
    links:
      - elasticsearch:elasticsearch
    logging:
      driver: none 
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/ --config.reload.automatic
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_SECURITY_ENABLED: "false"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
  filebeat:
    image: bargenson/filebeat
    environment:
      - "LOGSTASH_HOST=logstash"
      - "LOGSTASH_PORT=5044"
      - "SHIPPER_NAME=${hostname}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - "9200:9200"
    logging:
      driver: none 
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - "xpack.security.enabled=false"   
networks:
  default:
    external:
      name: ${COMPOSE_NETWORK}    
