version: '2'
services:
  naxsi:
    build: ./proxy
    ports:
      - "80:80"
    environment:
      PROXY_REDIRECT_IP: "13.95.222.243"

networks:
  default:
    external:
      name: ${COMPOSE_NETWORK}
