version: '2'
services:
  naxsi:
    build: ./proxy
    ports:
      - "80:80"
    environment:
      BACKEND_IP: "13.95.222.243"
      LEARNING_MODE : "no"
    external_links:
      - elasticsearch:elasticsearch

networks:
  default:
    external:
      name: ${COMPOSE_NETWORK}
