version: '2'
services:
  naxsi:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    environment:
      BACKEND_IP: "10.2.40.102:83"
      LEARNING_MODE : "yes"
    external_links:
      - elasticsearch:elasticsearch

networks:
  default:
    external:
      name: "elkstack_monitoring"
