version: '2'
services:
   plop:
    image: alpine
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "staging"
    external_links:
      - logstash
    command: /bin/sh -c "while true; do echo My Message `date`; sleep 1; done;"
    
networks:
  default:
    external:
      name: ${COMPOSE_NETWORK}


